# basic options
title: 5atoshiNakamoto | â‚¿ 2014
author: 51AE7F503F5F6404FBEC93CBF57AC7F1926025C3
email: 5atoshiNakamoto+Github@simplelogin.com
description: 5atoshiNakamoto's Warrant Canary Archive
social:
  github: https://github.com/5atoshiNakamoto

# Build settings
markdown: kramdown
theme: minima
