# basic options
title: 5atoshiNakamoto | â‚¿ 2014
author: F57A C7F1 9260 25C3
email: 5atoshiNakamoto+pgp@simplelogin.com
description: Warrant Canary Archive

# Build settings
markdown: kramdown
theme: minima
